<?php
/**
 * This file is part of the Orangecat PurchaseOrder package.
 *
 * (c) Oliverio Gombert <olivertar@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Orangecat\PurchaseOrder\ViewModel\Checkout\Success $viewModel */
$viewModel = $block->getViewModel();
$poId = $viewModel->getPurchaseOrderId();
$poIncrementId = $viewModel->getPurchaseOrderIncrementId();
?>
<?php if ($poId): ?>
    <div class="checkout-success">
        <h1 class="page-title">
            <span class="base" data-ui-id="page-title-wrapper">
                <?= $escaper->escapeHtml(__('Your purchase order has been received.')) ?>
            </span>
        </h1>
        <div class="message success">
            <div><?= $escaper->escapeHtml(__('Your purchase order number is: %1.', $poIncrementId)) ?></div>
            <div><?= $escaper->escapeHtml(__('It is currently pending approval.')) ?></div>
        </div>
        <p><?= $escaper->escapeHtml(__('We\'ll email you a confirmation when your order is approved.')) ?></p>
    </div>
<?php endif; ?>
