<?php
/**
 * This file is part of the Orangecat PurchaseOrder package.
 *
 * (c) Oliverio Gombert <olivertar@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/** @var \Orangecat\PurchaseOrder\Block\Order\ListOrder $block */
$purchaseOrders = $block->getPurchaseOrders();
?>
<div class="table-wrapper orders-history">
    <?php if ($purchaseOrders && count($purchaseOrders)): ?>
        <table class="data table table-order-items history" id="my-purchase-orders-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('Purchase Orders')) ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col id"><?= $block->escapeHtml(__('PO #')) ?></th>
                    <th scope="col" class="col date"><?= $block->escapeHtml(__('Date')) ?></th>
                    <th scope="col" class="col shipping"><?= $block->escapeHtml(__('Ship To')) ?></th>
                    <th scope="col" class="col total"><?= $block->escapeHtml(__('Order Total')) ?></th>
                    <th scope="col" class="col status"><?= $block->escapeHtml(__('Status')) ?></th>
                    <th scope="col" class="col actions"><?= $block->escapeHtml(__('Action')) ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($purchaseOrders as $po): ?>
                    <tr>
                        <td data-th="<?= $block->escapeHtml(__('PO #')) ?>" class="col id"><?= $block->escapeHtml($po->getIncrementId()) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date"><?= $block->escapeHtml($po->getCreatedAt()) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Ship To')) ?>" class="col shipping"><?= /* @noEscape */ $po->getGrandTotal() > 0 ? __('Company Office') : '' ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Order Total')) ?>" class="col total"><?= /* @noEscape */ $block->escapeHtml($this->helper(\Magento\Framework\Pricing\Helper\Data::class)->currency($po->getGrandTotal(), true, false)) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status"><?= $block->escapeHtml($block->getStatusLabel($po->getStatus())) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Action')) ?>" class="col actions">
                            <a href="<?= $block->escapeUrl($block->getViewUrl($po)) ?>" class="action view">
                                <span><?= $block->escapeHtml(__('View Order')) ?></span>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php else: ?>
        <div class="message info empty"><span><?= $block->escapeHtml(__('You have no purchase orders.')) ?></span></div>
    <?php endif; ?>
</div>
<div class="actions-toolbar">
    <div class="secondary">
        <a class="action back" href="<?= $block->escapeUrl($block->getUrl('customer/account')) ?>">
            <span><?= $block->escapeHtml(__('Back')) ?></span>
        </a>
    </div>
</div>
